CREATE TABLE `Meals` (
  `id` INTEGER NULL  DEFAULT NULL,
  `name_meal` VARCHAR(50) NULL DEFAULT NULL,
  `id_Chefs` INTEGER NULL DEFAULT NULL,
  `id_Categories` INTEGER UNIQUE NOT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);